server:
  port: 8080
spring:
  data:
    mongodb:
      username: root
      password: example
      port: 27017
      host: localhost
      database: example-project
      authentication-database: admin
    #Now add redis - this is a cache so we dont access db with every request
    redis:
      host: localhost
      port: 6379
#just make your first create and it works