#run this config when using intellij

server:
  port: 8080
spring:
  data:
    mongodb:
      username: root
      password: example
      port: 27017
      host: localhost
      database: example-project
      authentication-database: admin